### ISSUE TITLE
[Feature request] - pod不下啦呀

### ISSUE THREAD

**Issue by tangbing** [lagoueduCol/iOS-linyongjian#28]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/11678386/116817173-b8933a80-ab97-11eb-8707-9e51f2a3ce05.png">

 在拉钩买了你的课程，想跑一下源码，如图，pod 几次了，pod不来，能否带pod源码提交，不忽略pod

**Comment by JakeLin** [comment]
我不推荐把 Pod 源码放 Repo 呀，试一下梯子？

**Comment by wustzhy** [comment]
git config --global http.postBuffer 4194304000
