### ISSUE TITLE
[Feature request] - 

### ISSUE THREAD

**Issue by tangbing** [lagoueduCol/iOS-linyongjian#29]
只写了半年的swift，看了Moments swift源码，有些看不懂，比如
<img width="923" alt="image" src="https://user-images.githubusercontent.com/11678386/118685838-036aae80-b836-11eb-9ef4-17e98eea76c8.png">
这个query是啥意思？

还有就是，看到项目中很多swift面向协议的思想，怎么在swift培养这种思想呢？

**Comment by JakeLin** [comment]
> 这个query是啥意思？

Moments 使用了 GraphQL，请看《第 18 讲| 网络层架构：如何设计网络访问与 JSON 数据解析？》，里面有详细讲述 `query` 的意思。 

> 还有就是，看到项目中很多swift面向协议的思想，怎么在swift培养这种思想呢？

建议要看，多想和多写，课程中好几动手题都涉及到如何把面向协议的思想应用到项目中。
