### ISSUE TITLE
项目跑不起来,希望林老师和各位同学帮忙看下

### ISSUE THREAD

**Issue by CoderKingXY** [lagoueduCol/iOS-linyongjian#36]
环境搭建好之后，执行`./scripts/setup.sh `脚本后报错。
操作系统版本是MacOS Monterey 12.0.1，M1芯片，Xcode版本是13.1, Cocoapods 版本是1.11.2。

错误日志：

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=859%3A+unexpected+token+at+%27%7B%0A++%22name%22%3A+%22GoogleDataTransport%22%2C%0A++%22version%22%3A+%228.0.0%22%2C%0A++%22summary%22%3A+%22Google+iOS+SDK+data+transport.%22%2C%0A++%22description%22%3A+%22Shared+library+for+iOS+SDK+data+transport+needs.%22%2C%0A++%22homepage%22%3A+%22https%3A%2F%2Fdevelopers.google.com%2F%22%2C%0A++%22license%22%3A+%7B%0A++++%22type%22%3A+%22Apache%22%2C%0A++++%22file%22%3A+%22LICENSE%22%0A++%7D%2C%0A++%22authors%22%3A+%22Google%2C+Inc.%22%2C%0A++%22source%22%3A+%7B%0A++++%22git%22%3A+%22https%3A%2F%2Fgithub.com%2Ffirebase%2Ffirebase-ios-sdk.git%22%2C%0A++++%22tag%22%3A+%22DataTransport-8.0.0%22%0A++%7D%2C%0A++%22platforms%22%3A+%7B%0A++++%22ios%22%3A+%229.0%22%2C%0A++++%22osx%22%3A+%2210.12%22%2C%0A++++%22tvos%22%3A+%2210.0%22%2C%0A++++%22watchos%22%3A+%226.0%22%0A++%7D%2C%0A++%22cocoapods_version%22%3A+%22%3E%3D+1.4.0%22%2C%0A++%22prefix_header_file%22%3A+false%2C%0A++%22source_files%22%3A+%5B%0A++++%22GoogleDataTransport%2FGDTCORLibrary%2F%2A%2A%2F%2A%22%2C%0A++++%22GoogleDataTransport%2FGDTCCTLibrary%2F%2A%2A%2F%2A%22%0A++%5D%2C%0A++%22public_header_files%22%3A+%22GoogleDataTransport%2FGDTCORLibrary%2FPublic%2FGoogleDataTransport%2F%2A.h%22%2C%0A++%22ios%22%3A+%7B%0A++++%22frameworks%22%3A+%5B%0A++++++%22SystemConfiguration%22%2C%0A++++++%22CoreTelephony%22%0A++++%5D%0A++%7D%2C%0A++%22osx%22%3A+%7B%0A++++%22frameworks%22%3A+%5B%0A++++++%22SystemConfiguration%22%2C%0A++++++%22CoreTelephony%22%0A++++%5D%0A++%7D%2C%0A++%22tvos%22%3A+%7B%0A++++%22frameworks%22%3A+%22SystemConfiguration%22%0A++%7D%2C%0A++%22libraries%22%3A+%5B%0A++++%22z%22%0A++%5D%2C%0A++%22dependencies%22%3A+%7B%0A++++%22nanopb%22%3A+%5B%0A++++++%22~%3E+2.30906.0%22%0A++++%5D%0A++%7D%2C%0A++%22pod_target_xcconfig%22%3A+%7B%0A++++%22GCC_C_LANGUAGE_STANDARD%22%3A+%22c99%22%2C%0A++++%22GCC_TREAT_WARNINGS_AS_ERRORS%22%3A+%22YES%22%2C%0A++++%22CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY%22%3A+%22YES%22%2C%0A++++%22GCC_PREPROCESSOR_DEFINITIONS%22%3A+%22PB_FIELD_32BIT%3D1+PB_NO_PACKED_STRUCTS%3D1+PB_ENABLE_MALLOC%3D1+GDTCOR_VERSION%3D8.0.0%22%2C%0A++++%22HEADER_SEARCH_PATHS%22%3A+%22%5C%22%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by JakeLin** [comment]
目前我无法从上述的描述看到有效信息，能不能在 /setup.sh 里面一行行加 debug 信息，定位哪里出错？谢谢

**Comment by Lucky-JY** [comment]
> 目前我无法从上述的描述看到有效信息，能不能在 /setup.sh 里面一行行加 debug 信息，定位哪里出错？谢谢

我把setup.sh里面的指令分开执行。可以确定是最后一步报错了，即执行“bundle exec pod install”报错。我把终端的日志拷贝如下：

wxy@wangxiaoyudeMBP iOS-linyongjian % bundle exec pod install
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/wxy/.rbenv/versions/2.7.2/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin21]
    RubyGems : 3.1.4
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /Users/wxy/.rbenv/versions/2.7.2/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 5513c3988eaf4792b657991216ec514dc8f23ae1

               jd-ibkfxhbqmobileshop-ibkfxhbqmobileshop_spec - git - https://coding.jd.com/IBKFXHBQMobileshop/IBKFXHBQMobileshop_spec.git @ f0e464c4fe706f83677a0cc784c238281046dd8e

               jd-ibkfxhjdapp-ibkfxhjdapp_spec - git - http://coding.jd.com/IBKFXHjdapp/IBKFXHjdapp_spec.git @ 7f8636c05ce03e7c3d2307d997b9335cd7799541

               jd-ibkfxhjdb2b-ibkfxhjdb2b_spec - git - http://coding.jd.com/IBKFXHjdb2b/IBKFXHjdb2b_spec.git @ 13068234f5bbf583454f1a88bcdfc339e4b2c241

               jd-ibkfxhjdb2bshop-ibkfxhjdb2bshop_spec - git - https://coding.jd.com/IBKFXHjdb2bshop/IBKFXHjdb2bshop_spec.git @ a90a3eb05a79fe9dd71d177d087cc77c14c07744

               jd-ibkfxhjdbase-ibkfxhjdbase_spec - git - http://coding.jd.com/IBKFXHjdbase/IBKFXHjdbase_spec.git @ 070acf6ac1580bdfb6bab20793d695d9a3b8f3df

               jd-ibkfxhjddylib-ibkfxhjddylib_spec - git - http://coding.jd.com/IBKFXHJDDylib/IBKFXHJDDylib_spec.git @ b9656c636f072a83b940b27a292e0406f3e61d39

               jd-ibkfxhjdinternethospital-ibkfxhjdinternethospital_spec - git - http://coding.jd.com/IBKFXHJDInternetHospital/IBKFXHJDInternetHospital_spec.git @ 82487d0fcef45a5182c6bdf27a366558964b6843

               jd-ibkfxhjdthirdparty-ibkfxhjdthirdparty_spec - git - http://coding.jd.com/IBKFXHjdThirdParty/IBKFXHjdThirdParty_spec.git @ 2afa0e19d508a7ccb1375d494824f42c2f9c97d8

               jd-ibkfxhjingmai-ibkfxhjingmai_spec - git - http://coding.jd.com/IBKFXHjingmai/IBKFXHjingmai_spec.git @ 4a94000a49e07d25b68a386bdc091943267fa2f8

               jd-ibkfxhjpwhaleauction-ibkfxhjpwhaleauction_spec - git - http://coding.jd.com/IBKFXHJPWhaleAuction/IBKFXHJPWhaleAuction_spec.git @ efe83be9724e96e4204ad0e0139ddff5887fff1d

               jd-ibkfxhtestproject-ibkfxhtestproject_spec - git - http://coding.jd.com/IBKFXHTestProject/IBKFXHTestProject_spec.git @ d55646b7e4a3464d06099f1ecf4c525c98b0c19c

               jd-jdb2bshop-jdb2bshop_spec - git - https://git.jd.com/jdb2bshop/jdb2bshop_spec.git @ 63bc761063293c680f964d4dccdabcec6d206703

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://cdn.cocoapods.org/'

workspace './Moments.xcworkspace'
project './Moments/Moments.xcodeproj'

platform :ios, '14.0'
use_frameworks!

# ignore all warnings from all dependencies
inhibit_all_warnings!

def dev_pods
  pod 'SwiftLint', '= 0.42.0', configurations: ['Debug']
  pod 'SwiftGen', '= 6.4.0', configurations: ['Debug']
end

def core_pods
  pod 'RxSwift', '= 5.1.1'
  pod 'RxRelay', '= 5.1.1'
  pod 'Alamofire', '= 5.3.0'
end

def thirdparty_pods
  pod 'Firebase/Analytics', '= 7.0.0'
  pod 'Firebase/Crashlytics', '= 7.0.0'
  pod 'Firebase/RemoteConfig', '= 7.0.0'
  pod 'Firebase/Performance', '= 7.0.0'
end

def ui_pods
  pod 'SnapKit', '= 5.0.1'
  pod 'Kingfisher', '= 5.15.6'
  pod 'RxCocoa', '= 5.1.1'
  pod 'RxDataSources', '= 4.0.1'
end

def internal_pods
  pod 'DesignKit', :path => './Frameworks/DesignKit', :inhibit_warnings => false 
end

def test_pods
  pod 'Quick', '= 3.0.0'
  pod 'Nimble', '= 9.0.0'
  pod 'RxTest', '= 5.1.1'
  pod 'RxBlocking', '= 5.1.1'
end

target 'Moments' do
  dev_pods
  core_pods
  thirdparty_pods
  ui_pods
  internal_pods
end

target 'MomentsTests' do
  core_pods
  thirdparty_pods
  test_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
```

### Error

```
JSON::ParserError - 859: unexpected token at '{
  "name": "GoogleDataTransport",
  "version": "8.0.0",
  "summary": "Google iOS SDK data transport.",
  "description": "Shared library for iOS SDK data transport needs.",
  "homepage": "https://developers.google.com/",
  "license": {
    "type": "Apache",
    "file": "LICENSE"
  },
  "authors": "Google, Inc.",
  "source": {
    "git": "https://github.com/firebase/firebase-ios-sdk.git",
    "tag": "DataTransport-8.0.0"
  },
  "platforms": {
    "ios": "9.0",
    "osx": "10.12",
    "tvos": "10.0",
    "watchos": "6.0"
  },
  "cocoapods_version": ">= 1.4.0",
  "prefix_header_file": false,
  "source_files": [
    "GoogleDataTransport/GDTCORLibrary/**/*",
    "GoogleDataTransport/GDTCCTLibrary/**/*"
  ],
  "public_header_files": "GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/*.h",
  "ios": {
    "frameworks": [
      "SystemConfiguration",
      "CoreTelephony"
    ]
  },
  "osx": {
    "frameworks": [
      "SystemConfiguration",
      "CoreTelephony"
    ]
  },
  "tvos": {
    "frameworks": "SystemConfiguration"
  },
  "libraries": [
    "z"
  ],
  "dependencies": {
    "nanopb": [
      "~> 2.30906.0"
    ]
  },
  "pod_target_xcconfig": {
    "GCC_C_LANGUAGE_STANDARD": "c99",
    "GCC_TREAT_WARNINGS_AS_ERRORS": "YES",
    "CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY": "YES",
    "GCC_PREPROCESSOR_DEFINITIONS": "PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1 GDTCOR_VERSION=8.0.0",
    "HEADER_SEARCH_PATHS": "\"'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/json-2.6.1/lib/json/common.rb:216:in `parse'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/json-2.6.1/lib/json/common.rb:216:in `parse'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:748:in `from_string'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:722:in `from_file'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:188:in `specification'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/2.7.0/delegate.rb:342:in `block in delegating_block'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/2.7.0/delegate.rb:343:in `block in delegating_block'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:796:in `locked_requirement_possibility_set'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:776:in `possibilities_for_requirement'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:696:in `attempt_to_filter_existing_spec'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:672:in `attempt_to_activate'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/Users/wxy/.rbenv/versions/2.7.2/bin/pod:23:in `load'
/Users/wxy/.rbenv/versions/2.7.2/bin/pod:23:in `<top (required)>'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `load'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in `run'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in `exec'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/wxy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
/Users/wxy/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/Users/wxy/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=859%3A+unexpected+token+at+%27%7B%0A++%22name%22%3A+%22GoogleDataTransport%22%2C%0A++%22version%22%3A+%228.0.0%22%2C%0A++%22summary%22%3A+%22Google+iOS+SDK+data+transport.%22%2C%0A++%22description%22%3A+%22Shared+library+for+iOS+SDK+data+transport+needs.%22%2C%0A++%22homepage%22%3A+%22https%3A%2F%2Fdevelopers.google.com%2F%22%2C%0A++%22license%22%3A+%7B%0A++++%22type%22%3A+%22Apache%22%2C%0A++++%22file%22%3A+%22LICENSE%22%0A++%7D%2C%0A++%22authors%22%3A+%22Google%2C+Inc.%22%2C%0A++%22source%22%3A+%7B%0A++++%22git%22%3A+%22https%3A%2F%2Fgithub.com%2Ffirebase%2Ffirebase-ios-sdk.git%22%2C%0A++++%22tag%22%3A+%22DataTransport-8.0.0%22%0A++%7D%2C%0A++%22platforms%22%3A+%7B%0A++++%22ios%22%3A+%229.0%22%2C%0A++++%22osx%22%3A+%2210.12%22%2C%0A++++%22tvos%22%3A+%2210.0%22%2C%0A++++%22watchos%22%3A+%226.0%22%0A++%7D%2C%0A++%22cocoapods_version%22%3A+%22%3E%3D+1.4.0%22%2C%0A++%22prefix_header_file%22%3A+false%2C%0A++%22source_files%22%3A+%5B%0A++++%22GoogleDataTransport%2FGDTCORLibrary%2F%2A%2A%2F%2A%22%2C%0A++++%22GoogleDataTransport%2FGDTCCTLibrary%2F%2A%2A%2F%2A%22%0A++%5D%2C%0A++%22public_header_files%22%3A+%22GoogleDataTransport%2FGDTCORLibrary%2FPublic%2FGoogleDataTransport%2F%2A.h%22%2C%0A++%22ios%22%3A+%7B%0A++++%22frameworks%22%3A+%5B%0A++++++%22SystemConfiguration%22%2C%0A++++++%22CoreTelephony%22%0A++++%5D%0A++%7D%2C%0A++%22osx%22%3A+%7B%0A++++%22frameworks%22%3A+%5B%0A++++++%22SystemConfiguration%22%2C%0A++++++%22CoreTelephony%22%0A++++%5D%0A++%7D%2C%0A++%22tvos%22%3A+%7B%0A++++%22frameworks%22%3A+%22SystemConfiguration%22%0A++%7D%2C%0A++%22libraries%22%3A+%5B%0A++++%22z%22%0A++%5D%2C%0A++%22dependencies%22%3A+%7B%0A++++%22nanopb%22%3A+%5B%0A++++++%22~%3E+2.30906.0%22%0A++++%5D%0A++%7D%2C%0A++%22pod_target_xcconfig%22%3A+%7B%0A++++%22GCC_C_LANGUAGE_STANDARD%22%3A+%22c99%22%2C%0A++++%22GCC_TREAT_WARNINGS_AS_ERRORS%22%3A+%22YES%22%2C%0A++++%22CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY%22%3A+%22YES%22%2C%0A++++%22GCC_PREPROCESSOR_DEFINITIONS%22%3A+%22PB_FIELD_32BIT%3D1+PB_NO_PACKED_STRUCTS%3D1+PB_ENABLE_MALLOC%3D1+GDTCOR_VERSION%3D8.0.0%22%2C%0A++++%22HEADER_SEARCH_PATHS%22%3A+%22%5C%22%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
wxy@wangxiaoyudeMBP iOS-linyongjian % 


以上就是错误日志。折腾好久了，就是不知道哪里出问题了。

**Comment by JakeLin** [comment]
是不是需要梯子的缘故，一些 Firebase 的依赖找不到了？

另外一点，我不是很明白为什么指向了 https://coding.jd.com ？ 我的项目没有使用 jd 相关的组件。

**Comment by CoderKingXY** [comment]
> 是不是需要梯子的缘故，一些 Firebase 的依赖找不到了？
> 
> 另外一点，我不是很明白为什么指向了 https://coding.jd.com ？ 我的项目没有使用 jd 相关的组件。

经过了一番折腾，问题解决了。

我是这么折腾的：卸载rbenv、bundler、homebrew、cocoapods。

1. 安装rvm，作为ruby环境切换工具。安装ruby-2.7.2。
2. 切换ruby环境为2.7.2，使用gem安装cocoapods和bundler。
3. （这一步比较关键，可能问题就是出在这理，索性都删除重来了）`rm -rf ~/.cocoapods/repos/trunk/`，`rm -f ~/.cocoapods/repos/Spec_Lock`。
4. 在项目根目录执行`bundle install`和`bundle exec pod install`。


最后，感谢林老师的回复！

**Comment by JakeLin** [comment]
@Lucky-JY 谢谢你的反馈，请问你的 Machine 是不是本身安装了 RVM，然后和 rbenv 冲突了，我们的 Machine 一般只装一个 Ruby 环境，例如 rbenv。环境问题确实很难解决，因为每个人都不一样，问题不容易重现。所以我在第一章讲述如何搭建统一的开发环境，希望能为团队节省大量 troubleshooting 的时间。
